### ISSUE TITLE
Asteroids don't seem to generate deep deposits

### ISSUE THREAD

**Issue by Draxtheros** [SS13-Quadrant/Persistence-QuadA#6]
#### Description of issue
In my mining adventures no deep deposits could be located via scanning. Only surface deposits were found

#### Difference between expected and actual behavior
Big deposits should spawn in the rocks

#### Steps to reproduce 
Fling yourself off the station
Scan the rocks repeatedly
Find nothing

#### Length of time in which bug has been known to occur
10/26

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [x] Issue happened recently (less than 7 days ago)
- [x] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Dimasw99** [comment]
Issue got resolved. Turns out wee also needed to generate a deep ore map seperatly. Also do not forget that the drill requires a 2 tile radius of asteroid turf around it to work
